package rs.banka4.user_service.dto.requests;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

@Schema(description = "TOTP event validation request")
public record VerificationRequestDto (
    @NotNull(message = "Event ID cannot be null")
    @NotBlank(message = "Event ID is required")
    @Schema(description = "Event ID used when it is created", example = "550e8400-e29b-41d4-a716-446655440000")
    String eventId,
    @Schema(description = "TOTP code generated by the setup verification app", example = "123 456")
    @NotBlank(message = "TOTP code content is required")
    @NotNull(message = "TOTP code cannot be null")
    String code
) {

}
